services:
  rest:
    image: localhost:5000/pro-legacy_backend
    build:
      dockerfile: Dockerfile
      target: rest
  web:
    image: localhost:5000/pro-legacy_front
    build:
      dockerfile: Dockerfile
      target: front
