server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: pro_legacy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        default_schema: pro_legacy
    database: postgresql
  mail:
    host: smtp.mail.ru
    port: 465
    username: prolegacytest@mail.ru
    password: Wkemu4JiEptBvrsnM261
    protocol: smtp
    tls: true
    debug: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  servlet.multipart.max-file-size: 10MB
  servlet.multipart.max-request-size: 10MB
  devtools:
    restart:
      enabled: false
auth:
  admin-role: admin
  default-role: user
  jwt-secret: sTcIbJgW4pmMl9EHCpHnw+fUz/vX7dr6LpK2AdoPiLNrTT0fLyAga1dktkeqwiBg
  jwt-expiration-minutes: 60
  password-restoration-code-expiration-minutes: 15
bot:
  enabled: false
  creator-id: 1661612746 # ??? ??, ?? ???????, ??? (??????)
  name: ProLegacyBot
  token: 6748231331:AAEN53y3TBQIjdG0SpogUafJcVHV6zpxMxs

js-evaluator:
  timeout-seconds: 86400

api-url: http://localhost:10240/check
